tributo/config/routes.rb
Tributo::Application.routes.draw do
  root :to => "pagos#index"
  resources :pagos

  resources :personas

end

tributo/app/models/pago.rb
class Pago < ActiveRecord::Base

  attr_accessible :arbitrio, :mora, :persona_id
  belongs_to :persona

end

tributo/app/models/persona.rb
class Persona < ActiveRecord::Base
  attr_accessible :dni
  has_many :pagos
end

tributo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

tributo/app/controllers/pagos_controller.rb
class PagosController < ApplicationController
  # GET /pagos
  # GET /pagos.json
  def index
    @pagos = Pago.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pagos }
    end
  end

  # GET /pagos/1
  # GET /pagos/1.json
  def show
    @pago = Pago.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pago }
    end
  end

  # GET /pagos/new
  # GET /pagos/new.json
  def new
    @pago = Pago.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pago }
    end
  end

  # GET /pagos/1/edit
  def edit
    @pago = Pago.find(params[:id])
  end

  # POST /pagos
  # POST /pagos.json
  def create
    @pago = Pago.new(params[:pago])

    respond_to do |format|
      if @pago.save
        format.html { redirect_to @pago, notice: 'Pago was successfully created.' }
        format.json { render json: @pago, status: :created, location: @pago }
      else
        format.html { render action: "new" }
        format.json { render json: @pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pagos/1
  # PUT /pagos/1.json
  def update
    @pago = Pago.find(params[:id])

    respond_to do |format|
      if @pago.update_attributes(params[:pago])
        format.html { redirect_to @pago, notice: 'Pago was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagos/1
  # DELETE /pagos/1.json
  def destroy
    @pago = Pago.find(params[:id])
    @pago.destroy

    respond_to do |format|
      format.html { redirect_to pagos_url }
      format.json { head :no_content }
    end
  end
end

tributo/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personas }
    end
  end

  def total
    @total = @persona.pagos.sum(:mora)
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])

    total

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/new
  # GET /personas/new.json
  def new
    @persona = Persona.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(params[:persona])

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'DNI de Persona fue creada satisfactoriamente.' }
        format.json { render json: @persona, status: :created, location: @persona }
      else
        format.html { render action: "new" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personas/1
  # PUT /personas/1.json
  def update
    @persona = Persona.find(params[:id])

    respond_to do |format|
      if @persona.update_attributes(params[:persona])
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :no_content }
    end
  end
end

tributo/app/helpers/application_helper.rb
module ApplicationHelper
end

tributo/app/helpers/pagos_helper.rb
module PagosHelper
end

tributo/app/helpers/personas_helper.rb
module PersonasHelper
end

tributo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tributo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tributo/app/views/pagos/_form.html.erb
<%= form_for(@pago) do |f| %>
  <% if @pago.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pago.errors.count, "error") %> prohibited this pago from being saved:</h2>

      <ul>
      <% @pago.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arbitrio %><br />
    <%= f.number_field :arbitrio %>
  </div>
  <div class="field">
    <%= f.label :mora %><br />
    <%= f.number_field :mora %>
  </div>

  <div class="field">
    <%= f.label :persona %><br />
    <%= f.collection_select :persona_id, Persona.all, :id, :dni, :prompt => true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tributo/app/views/pagos/edit.html.erb
<h1>Editing pago</h1>

<%= render 'form' %>

<%= link_to 'Show', @pago %> |
<%= link_to 'Back', pagos_path %>

tributo/app/views/pagos/index.html.erb
<h1>Tributos</h1>

<table>
  <tr>
    <th>Arbitrio</th>
    <th>Mora</th>
    <th>DNI</th>
    <th></th>
    <th></th>
  </tr>

<% @pagos.each do |pago| %>
  <tr>
    <td><%= pago.arbitrio %></td>
    <td><%= pago.mora %></td>
    <td><%= pago.persona.dni %></td>
    <td><%= link_to 'Mostrar', pago %></td>
    <td><%= link_to 'Editar', edit_pago_path(pago) %></td>
    <td><%= link_to 'Eliminar', pago, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Ingresar nuevo tributo', new_pago_path %>

tributo/app/views/pagos/new.html.erb
<h1>Nuevo Tributo</h1>

<%= render 'form' %>

<%= link_to 'Back', pagos_path %>

tributo/app/views/pagos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arbitrio:</b>
  <%= @pago.arbitrio %>
</p>

<p>
  <b>Mora:</b>
  <%= @pago.mora %>
</p>


<%= link_to 'Edit', edit_pago_path(@pago) %> |
<%= link_to 'Back', pagos_path %>

tributo/app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dni %><br />
    <%= f.number_field :dni %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tributo/app/views/personas/edit.html.erb
<h1>Editando DNI</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @persona %> |
<%= link_to 'Regresa', personas_path %>

tributo/app/views/personas/index.html.erb
<h1>Lista de Ciudadanos</h1>

<table>
  <tr>
    <th>DNI</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personas.each do |persona| %>
  <tr>
    <td><%= persona.dni %></td>
    <td><%= link_to 'Mostrar', persona %></td>
    <td><%= link_to 'Editar', edit_persona_path(persona) %></td>
    <td><%= link_to 'Eliminar', persona, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo DNI', new_persona_path %>

tributo/app/views/personas/new.html.erb
<h1>Nuevo DNI</h1>

<%= render 'form' %>

<%= link_to 'Regresa', personas_path %>

tributo/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>DNI:</b>
  <%= @persona.dni %>
</p>

<table>
	<%@ persona.pagos.each do |pago| %>
	<tr>
		<td><%=pago.arbitrio %></td>
		<td><%=pago.mora %></td>
	</tr>
	<%end%>
</table>

<%= @total %><br/>

<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Regresa', personas_path %>